version: "3"
services:
  backend:
    build: ./be
    restart: always
    working_dir: /app
    volumes:
      - ./be:/app
      - ~/.aws:/root/.aws
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      ENDPOINT: http://localhost:5000/
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
